# Generated by Django 2.2.4 on 2020-07-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faves_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.CharField(default='Las Vegas', max_length=100),
            preserve_default=False,
        ),
    ]
