# Generated by Django 2.2.4 on 2020-07-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faves_app', '0004_likes_web_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='web_url',
        ),
    ]
